//! `builtin::TabView`/`TabViewItem`, their identity helpers, and the `ListExt` collection.

use super::NativeControl;
use crate::AnyView;
use crate::inner::InnerTabView;
use elwindui_core::ui::UIElementExt;
use std::any::Any;
use std::cell::{Cell, RefCell};
use std::rc::{Rc, Weak};

/// See docs/elwindui_builtins_spec.md 付録Y and `elwindui_backend_appkit::native_ui::TabView`'s
/// doc comment for the shared `children` convention (static and transparent dynamic ranges) and
/// why `TabViewItem` — not a bespoke per-mode representation — is the thing every child range
/// normalizes into. `Microsoft.UI.Xaml.Controls.
/// TabView` is a real native tabbed-document control (unlike AppKit, which has none, hence that
/// backend's hand-rolled `TabChip`/`TabStrip`), and each `TabViewItem`'s `Content` here is a live
/// `crate::host::TreeHostPanel` holding that tab's whole widget tree — recreating it on every
/// resync (as AppKit's *chips*, which are cheap, safely do) would reset a document's `TextArea`
/// (lost cursor/focus) on every keystroke. Unlike AppKit, this backend has **no** "content already
/// shown once" limitation for static mode: a `TabViewItem`'s `content` is moved into its own
/// persistent `TreeHostPanel` exactly once, when that `TabViewItem` is first inserted as a real
/// native tab — it is never subsequently discarded by selecting a different tab
/// (`Controls::TabView` shows/hides each item's own `Content` natively), so there's nothing to
/// restore. `struct_only = elwindui_core::ui::TabViewExt` (a deliberately empty shared trait — see
/// its own doc comment in `elwindui-core`) — mirrors `elwindui_backend_appkit::native_ui::TabView`'s
/// own shape; every method below stays `#[inherent]`, unchanged.
#[elwindui_macros::class(struct_only = elwindui_core::ui::TabViewExt, inherits = crate::NativeControl)]
pub struct TabView {
    inner: InnerTabView,
    children: RefCell<Vec<Rc<dyn elwindui_core::ui::TabViewItemExt>>>,
    /// Pointer identities (`Rc::as_ptr`, as `usize`) of the `TabViewItem`s currently reflected as
    /// real `TabViewItem`s, in display order — the "before" side of `rebuild`'s diff against the
    /// current `children` pointers (the "after" side).
    displayed: RefCell<Vec<usize>>,
    /// Not read by this type itself (`set_on_select` passes callbacks straight through to
    /// `crate::inner::InnerTabView`, which has no getter of its own) — tracked here purely so
    /// `selected_item`/`selected_container` can read it back.
    selected_index: Cell<usize>,
    on_close: RefCell<Option<Box<dyn Fn(usize)>>>,
    weak_self: RefCell<Weak<TabView>>,
}

/// The backend-native representation of one declarative `TabViewItem`, whether it was written
/// literally or generated by a transparent dynamic child range.
/// `struct_only = elwindui_core::ui::TabViewItemExt` (a deliberately empty shared trait — see its
/// own doc comment in `elwindui-core`) — mirrors `elwindui_backend_appkit::native_ui::TabViewItem`'s
/// own shape; every method below stays `#[inherent]`, unchanged.
#[elwindui_macros::class(struct_only = elwindui_core::ui::TabViewItemExt)]
pub struct TabViewItem {
    header: RefCell<String>,
    on_header_changed: RefCell<Option<Box<dyn Fn()>>>,
    // Taken (moved into a real `TreeHostPanel`) the first time this `TabViewItem` is inserted as a
    // displayed tab; `None` afterward — see `TabView`'s own doc comment for why that's never a
    // problem here (unlike AppKit's single shared content pane).
    content: RefCell<Option<Rc<dyn UIElementExt>>>,
    closable: Cell<bool>,
    on_close: RefCell<Option<Box<dyn Fn()>>>,
}

#[elwindui_macros::class]
impl TabViewItem {
    fn construct() -> Self {
        Self {
            header: RefCell::new(String::new()),
            on_header_changed: RefCell::new(None),
            content: RefCell::new(None),
            closable: Cell::new(true),
            on_close: RefCell::new(None),
        }
    }

    #[inherent]
    pub fn set_header(&self, header: &str) {
        if *self.header.borrow() == header {
            return;
        }
        *self.header.borrow_mut() = header.to_string();
        if let Some(callback) = self.on_header_changed.borrow().as_ref() {
            callback();
        }
    }

    #[inherent]
    pub fn set_content(&self, content: Rc<dyn UIElementExt>) {
        *self.content.borrow_mut() = Some(content);
    }

    #[inherent]
    pub fn set_closable(&self, closable: bool) {
        self.closable.set(closable);
    }

    #[inherent]
    pub fn set_on_close(&self, callback: Box<dyn Fn()>) {
        *self.on_close.borrow_mut() = Some(callback);
    }
}

#[elwindui_macros::class]
impl TabView {
    fn construct() -> Self {
        let inner = InnerTabView::new();
        let handle = inner.handle();
        Self {
            base: NativeControl::construct(handle),
            inner,
            children: RefCell::new(Vec::new()),
            displayed: RefCell::new(Vec::new()),
            selected_index: Cell::new(0),
            on_close: RefCell::new(None),
            weak_self: RefCell::new(Weak::new()),
        }
    }

    fn on_constructed(&self) {
        // `owner_rc()` is guaranteed `Some` here (see `Button::on_constructed`'s own doc comment);
        // downcasting the type-erased owner back to this concrete `TabView` is what lets `rebuild`/
        // `attach_header_listener`/`set_on_close` upgrade `weak_self` into a real `Rc<TabView>`
        // later.
        let node = self
            .as_ui_element()
            .visual_collection
            .owner_rc()
            .expect("TabView::on_constructed: object must already be Rc-constructed");
        let any_rc: Rc<dyn Any> = node;
        let this = any_rc
            .downcast::<TabView>()
            .expect("TabView::on_constructed: owner must be this TabView");
        *self.weak_self.borrow_mut() = Rc::downgrade(&this);
        // WinUI3's `TabView` is a tab stop by default — see
        // docs/elwindui_gui_framework_design.md §5.5.
        self.set_tab_stop(true);
    }

    #[inherent]
    pub fn set_children(&self, children: Vec<Rc<TabViewItem>>) {
        for item in &children {
            self.attach_header_listener(
                &(Rc::clone(item) as Rc<dyn elwindui_core::ui::TabViewItemExt>),
            );
        }
        *self.children.borrow_mut() = children
            .into_iter()
            .map(|item| item as Rc<dyn elwindui_core::ui::TabViewItemExt>)
            .collect();
        self.rebuild();
    }

    #[inherent]
    pub fn set_on_select(&self, callback: Box<dyn Fn(usize)>) {
        self.inner.set_on_select(callback);
    }

    /// A static `TabViewItem`'s own `on_close` (if set) takes precedence — it's the per-item
    /// declaration in that mode; dynamic mode has none, so its `TabView`-level `on_close(index)`
    /// is used instead (same precedence as `elwindui_backend_appkit::native_ui::TabView`).
    #[inherent]
    pub fn set_on_close(&self, callback: Box<dyn Fn(usize)>) {
        *self.on_close.borrow_mut() = Some(callback);
        let this = self.weak_self.borrow().clone();
        self.inner.set_on_close(Box::new(move |index| {
            let Some(this) = this.upgrade() else { return };
            let entry = this.children.borrow().get(index).cloned();
            let handled = entry.is_some_and(|e| {
                if let Some(cb) = downcast_tab_view_item(&*e).on_close.borrow().as_ref() {
                    cb();
                    true
                } else {
                    false
                }
            });
            if !handled {
                if let Some(cb) = this.on_close.borrow().as_ref() {
                    cb(index);
                }
            }
        }));
    }

    #[inherent]
    pub fn set_on_new_tab(&self, callback: Box<dyn Fn()>) {
        self.inner.set_on_new_tab(callback);
    }

    fn children(&self) -> &dyn elwindui_core::ui::ListExt<dyn elwindui_core::ui::TabViewItemExt> {
        self
    }

    /// Unlike `elwindui_backend_appkit::native_ui::TabView` (where selecting a tab means manually
    /// swapping the single visible content pane, done inside `rebuild`), `Controls::TabView`
    /// already shows/hides each `TabViewItem`'s own persistent `Content` based on `SelectedIndex`
    /// natively — so this is just a straight passthrough, no rebuild needed.
    #[inherent]
    pub fn set_selected_index(&self, selected_index: usize) {
        if self.selected_index.get() == selected_index {
            return;
        }
        self.selected_index.set(selected_index);
        self.inner.set_selected_index(selected_index);
    }

    #[inherent]
    pub fn into_any_view(&self) -> AnyView {
        self.inner.handle()
    }

    #[inherent]
    fn attach_header_listener(&self, item: &Rc<dyn elwindui_core::ui::TabViewItemExt>) {
        let key = tab_view_item_key(item);
        let weak = self.weak_self.borrow().clone();
        *downcast_tab_view_item(&**item)
            .on_header_changed
            .borrow_mut() = Some(Box::new(move || {
            if let Some(tab_view) = weak.upgrade() {
                tab_view.refresh_dynamic_header(key);
            }
        }));
    }

    #[inherent]
    fn refresh_dynamic_header(&self, key: usize) {
        let Some(index) = self
            .displayed
            .borrow()
            .iter()
            .position(|displayed| *displayed == key)
        else {
            return;
        };
        let Some(item) = self
            .children
            .borrow()
            .iter()
            .find(|item| tab_view_item_key(item) == key)
            .cloned()
        else {
            return;
        };
        self.inner
            .set_tab_title(index, &downcast_tab_view_item(&*item).header.borrow());
    }

    /// Keyed diff (pointer identity — see `displayed`'s doc comment): removes displayed tabs whose
    /// `TabViewItem` no longer appears in `children`, inserts a real `TabViewItem` (+ that entry's
    /// one-time `content`) for each not-yet-displayed one, and refreshes every displayed tab's
    /// title (labels can change independently of tab identity, e.g. a document's file name). Does
    /// not handle reordering existing tabs (no reorder op is exposed, and nothing in notepad's
    /// command set reorders tabs today — only appends/removes) — an already-displayed tab is left
    /// in its current slot rather than physically moved to match `children`' exact order.
    #[inherent]
    fn rebuild(&self) {
        let children = self.children.borrow();
        let new_keys: Vec<usize> = children.iter().map(tab_view_item_key).collect();
        let mut displayed = self.displayed.borrow_mut();

        for i in (0..displayed.len()).rev() {
            if !new_keys.contains(&displayed[i]) {
                self.inner.remove_tab_at(i);
                displayed.remove(i);
            }
        }

        for (target_index, (key, entry)) in new_keys.iter().zip(children.iter()).enumerate() {
            if !displayed.contains(key) {
                let entry = downcast_tab_view_item(&**entry);
                let label = entry.header.borrow().clone();
                let closable = entry.closable.get();
                let content_host =
                    self.inner
                        .insert_tab(target_index.min(displayed.len()), &label, closable);
                if let Some(content) = entry.content.borrow_mut().take() {
                    content_host.set_tree(content);
                }
                let insertion_index = target_index.min(displayed.len());
                displayed.insert(insertion_index, *key);
            }
        }
        drop(displayed);

        for (index, entry) in children.iter().enumerate() {
            self.inner
                .set_tab_title(index, &downcast_tab_view_item(&**entry).header.borrow());
        }
    }
}

pub(crate) fn downcast_tab_view_item(item: &dyn elwindui_core::ui::TabViewItemExt) -> &TabViewItem {
    item.as_any()
        .downcast_ref::<TabViewItem>()
        .expect("TabViewExt: child must be this backend's TabViewItem")
}

pub(crate) fn tab_view_item_key(item: &Rc<dyn elwindui_core::ui::TabViewItemExt>) -> usize {
    Rc::as_ptr(item) as *const () as usize
}

impl elwindui_core::ui::ListExt<dyn elwindui_core::ui::TabViewItemExt> for TabView {
    fn add(&self, item: Rc<dyn elwindui_core::ui::TabViewItemExt>) {
        self.attach_header_listener(&item);
        self.children.borrow_mut().push(item);
        self.rebuild();
    }

    fn insert(&self, index: usize, item: Rc<dyn elwindui_core::ui::TabViewItemExt>) {
        self.attach_header_listener(&item);
        let mut children = self.children.borrow_mut();
        let index = index.min(children.len());
        children.insert(index, item);
        drop(children);
        self.rebuild();
    }

    fn remove(&self, item: &Rc<dyn elwindui_core::ui::TabViewItemExt>) -> bool {
        let mut children = self.children.borrow_mut();
        let Some(index) = children.iter().position(|child| Rc::ptr_eq(child, item)) else {
            return false;
        };
        children.remove(index);
        drop(children);
        self.rebuild();
        true
    }

    fn remove_at(&self, index: usize) -> Rc<dyn elwindui_core::ui::TabViewItemExt> {
        let item = self.children.borrow_mut().remove(index);
        self.rebuild();
        item
    }

    fn clear(&self) {
        self.children.borrow_mut().clear();
        self.rebuild();
    }

    fn len(&self) -> usize {
        self.children.borrow().len()
    }
    fn is_empty(&self) -> bool {
        self.children.borrow().is_empty()
    }
    fn to_vec(&self) -> Vec<Rc<dyn elwindui_core::ui::TabViewItemExt>> {
        self.children.borrow().clone()
    }
}
