//! The WinRT seam: the erased native-element handle (`AnyView`) every other layer passes
//! around instead of a concrete XAML type, plus the `usize`-keyed UI-event callback registry the
//! generated WinRT handlers need (they require `Send`, which an `Rc`-holding closure is not).
//!
//! `AnyView` is re-exported at the crate root because `elwindui-codegen` generates references to
//! `elwindui::backend::AnyView` directly — that path must stay stable.

use crate::bindings::Microsoft::UI::Xaml::Controls::{
    Button as XamlButton, Canvas, CheckBox as XamlCheckBox, ComboBox as XamlComboBox,
    PasswordBox as XamlPasswordBox, RadioButton as XamlRadioButton, ScrollViewer,
    Slider as XamlSlider, TabView as XamlTabView, TextBox as XamlTextBox,
    ToggleSwitch as XamlToggleSwitch, ToolTip as XamlToolTip, ToolTipService,
};
use crate::bindings::Microsoft::UI::Xaml::FrameworkElement;
use elwindui_core::input::RawKeyEvent;
use std::cell::{Cell, RefCell};
use std::collections::HashMap;
use std::rc::Rc;
use std::sync::atomic::{AtomicUsize, Ordering};
use windows::Foundation::PropertyValue;
use windows::Foundation::Size;
use windows::core::{HSTRING, Interface};

pub(crate) static NEXT_UI_EVENT_CALLBACK: AtomicUsize = AtomicUsize::new(1);

thread_local! {
    /// WinRT delegates generated by `windows-bindgen` require `Send`, while elwindui's UI state is
    /// intentionally single-threaded (`Rc<RefCell<_>>`). WinUI invokes these delegates on this UI
    /// thread, so the delegate captures only a numeric key and resolves the actual callback here.
    static UI_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn()>>> = RefCell::new(HashMap::new());
    static UI_BOOL_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn() -> bool>>> = RefCell::new(HashMap::new());
    static UI_CONTEXT_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::ContextRequestedEventArgs)>>> = RefCell::new(HashMap::new());
    static UI_POINTER_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::PointerRoutedEventArgs)>>> = RefCell::new(HashMap::new());
    static UI_RIGHT_TAPPED_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs)>>> = RefCell::new(HashMap::new());
    static UI_INDEX_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn(usize)>>> = RefCell::new(HashMap::new());
    static UI_F32_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn(f32)>>> = RefCell::new(HashMap::new());
    static UI_SIZE_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn(f64, f64)>>> = RefCell::new(HashMap::new());
    static UI_KEY_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn(RawKeyEvent)>>> = RefCell::new(HashMap::new());
    static UI_TEXT_EVENT_CALLBACKS: RefCell<HashMap<usize, Rc<dyn Fn(String)>>> = RefCell::new(HashMap::new());
}

#[derive(Clone, Copy)]
enum UiCallbackKind {
    Event,
    BoolEvent,
    ContextEvent,
    PointerEvent,
    RightTapped,
    Index,
    Size,
    Key,
    Text,
}

#[derive(Default)]
struct UiCallbackRegistryOwnerInner {
    registrations: RefCell<Vec<(UiCallbackKind, usize)>>,
}

fn remove_ui_callback(kind: UiCallbackKind, id: usize) {
    let _ = match kind {
        UiCallbackKind::Event => UI_EVENT_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
        UiCallbackKind::BoolEvent => UI_BOOL_EVENT_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
        UiCallbackKind::ContextEvent => UI_CONTEXT_EVENT_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
        UiCallbackKind::PointerEvent => UI_POINTER_EVENT_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
        UiCallbackKind::RightTapped => UI_RIGHT_TAPPED_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
        UiCallbackKind::Index => UI_INDEX_EVENT_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
        UiCallbackKind::Size => UI_SIZE_EVENT_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
        UiCallbackKind::Key => UI_KEY_EVENT_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
        UiCallbackKind::Text => UI_TEXT_EVENT_CALLBACKS.try_with(|callbacks| {
            callbacks.borrow_mut().remove(&id);
        }),
    };
}

impl Drop for UiCallbackRegistryOwnerInner {
    fn drop(&mut self) {
        for (kind, id) in self.registrations.get_mut().drain(..) {
            remove_ui_callback(kind, id);
        }
    }
}

/// Owns callback-registry entries whose native event source has the same lifetime.
///
/// WinRT delegates capture only the numeric callback id because their generated ABI requires a
/// `Send` closure, while the callback itself deliberately remains UI-thread-local and may contain
/// `Rc` state. Clones share one registration set; dropping the final owner removes every entry so
/// a detached tree host or native child cannot keep callback closures (and anything they capture)
/// alive indefinitely. A delegate that races with teardown safely resolves the missing id as a
/// no-op through the existing `invoke_ui_*` functions.
#[derive(Clone, Default)]
pub(crate) struct UiCallbackRegistryOwner(Rc<UiCallbackRegistryOwnerInner>);

impl UiCallbackRegistryOwner {
    /// Removes every callback owned by this lifetime group while keeping the owner itself alive.
    ///
    /// This is used when a native source reports its terminal event but its event delegate still
    /// temporarily exists on the call stack. Clearing explicitly breaks the close-handler's
    /// self-retaining cycle; the `Drop` implementation remains the fallback for all other owners.
    pub(crate) fn clear(&self) {
        let registrations = self.0.registrations.replace(Vec::new());
        for (kind, id) in registrations {
            remove_ui_callback(kind, id);
        }
    }

    /// Registers a no-argument callback owned by this lifetime group.
    pub(crate) fn register_event(&self, callback: Rc<dyn Fn()>) -> usize {
        let id = register_ui_event_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::Event, id));
        id
    }

    /// Registers a no-argument boolean callback owned by this lifetime group.
    pub(crate) fn register_bool_event(&self, callback: Rc<dyn Fn() -> bool>) -> usize {
        let id = register_ui_bool_event_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::BoolEvent, id));
        id
    }

    /// Registers a ContextRequested callback owned by this lifetime group.
    pub(crate) fn register_context_event(
        &self,
        callback: Rc<
            dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::ContextRequestedEventArgs),
        >,
    ) -> usize {
        let id = register_ui_context_event_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::ContextEvent, id));
        id
    }

    /// Registers a pointer-routed callback owned by this lifetime group.
    pub(crate) fn register_pointer_event(
        &self,
        callback: Rc<dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::PointerRoutedEventArgs)>,
    ) -> usize {
        let id = register_ui_pointer_event_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::PointerEvent, id));
        id
    }

    /// Registers a RightTapped callback owned by this lifetime group.
    pub(crate) fn register_right_tapped(
        &self,
        callback: Rc<
            dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs),
        >,
    ) -> usize {
        let id = register_ui_right_tapped_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::RightTapped, id));
        id
    }

    /// Registers an index callback owned by this lifetime group.
    pub(crate) fn register_index(&self, callback: Rc<dyn Fn(usize)>) -> usize {
        let id = register_ui_index_event_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::Index, id));
        id
    }

    /// Registers a `(width, height)` size-changed callback owned by this lifetime group — e.g.
    /// `Window.SizeChanged` (Issue #225). Reuses the same `register_ui_size_event_callback` raw
    /// insert `Window.SizeChanged`'s own registration already called directly; the fix here is
    /// tracking the returned id in *this* owner's `registrations` (previously untracked, so the
    /// TLS entry — and everything it captured — outlived the owning `InnerWindow`).
    pub(crate) fn register_size(&self, callback: Rc<dyn Fn(f64, f64)>) -> usize {
        let id = register_ui_size_event_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::Size, id));
        id
    }

    /// Registers a raw-key callback owned by this lifetime group.
    pub(crate) fn register_key(&self, callback: Rc<dyn Fn(RawKeyEvent)>) -> usize {
        let id = register_ui_key_event_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::Key, id));
        id
    }

    /// Registers a text-input callback owned by this lifetime group.
    pub(crate) fn register_text(&self, callback: Rc<dyn Fn(String)>) -> usize {
        let id = register_ui_text_event_callback(callback);
        self.0
            .registrations
            .borrow_mut()
            .push((UiCallbackKind::Text, id));
        id
    }
}

pub(crate) fn register_ui_event_callback(callback: Rc<dyn Fn()>) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_event_callback(id: usize) {
    // Clone the `Rc` out and drop the borrow *before* calling it — the callback body (e.g. opening
    // a file, which can synchronously rebuild native controls and register new callbacks) can
    // legitimately re-enter `register_ui_event_callback`/this same map. Holding `borrow()` across
    // the call would make that a `RefCell` double-borrow panic (`already borrowed`), not just a
    // theoretical risk — reproduced via `notepad`'s File > Open.
    let callback = UI_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback();
    }
}

#[cfg(test)]
pub(crate) fn ui_event_callback_count() -> usize {
    UI_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().len())
}

pub(crate) fn register_ui_bool_event_callback(callback: Rc<dyn Fn() -> bool>) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_BOOL_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_bool_event_callback(id: usize) -> bool {
    let callback = UI_BOOL_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    callback.is_some_and(|callback| callback())
}

pub(crate) fn register_ui_context_event_callback(
    callback: Rc<dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::ContextRequestedEventArgs)>,
) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_CONTEXT_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_context_event_callback(
    id: usize,
    args: &crate::bindings::Microsoft::UI::Xaml::Input::ContextRequestedEventArgs,
) {
    let callback =
        UI_CONTEXT_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback(args);
    }
}

pub(crate) fn register_ui_pointer_event_callback(
    callback: Rc<dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::PointerRoutedEventArgs)>,
) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_POINTER_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_pointer_event_callback(
    id: usize,
    args: &crate::bindings::Microsoft::UI::Xaml::Input::PointerRoutedEventArgs,
) {
    let callback =
        UI_POINTER_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback(args);
    }
}

pub(crate) fn register_ui_right_tapped_callback(
    callback: Rc<dyn Fn(&crate::bindings::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs)>,
) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_RIGHT_TAPPED_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_right_tapped_callback(
    id: usize,
    args: &crate::bindings::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs,
) {
    let callback = UI_RIGHT_TAPPED_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback(args);
    }
}

pub(crate) fn register_ui_index_event_callback(callback: Rc<dyn Fn(usize)>) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_INDEX_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_index_event_callback(id: usize, index: usize) {
    // See `invoke_ui_event_callback`'s doc comment — same re-entrancy hazard, same fix.
    let callback = UI_INDEX_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback(index);
    }
}

pub(crate) fn register_ui_f32_event_callback(callback: Rc<dyn Fn(f32)>) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_F32_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_f32_event_callback(id: usize, value: f32) {
    // See `invoke_ui_event_callback`'s doc comment — same re-entrancy hazard, same fix.
    let callback = UI_F32_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback(value);
    }
}

/// Issue #225: `Window.SizeChanged`'s handler is `TypedEventHandler<IInspectable,
/// WindowSizeChangedEventArgs>` — a `Send`-bound WinRT delegate, same reason every other callback
/// in this file goes through this numeric-key indirection instead of capturing `Rc` state
/// directly. This is the low-level raw insert only — callers must go through
/// `UiCallbackRegistryOwner::register_size` (like `register_index`, above, wraps
/// `register_ui_index_event_callback`) so the returned id is tracked and removed when the owning
/// `Window`/`InnerWindow` drops; calling this directly, untracked, previously let the TLS entry
/// (and its captured `menu_wrapper`/`top_inset`/`Weak<TreeHostPanel>` state) outlive the `Window`.
pub(crate) fn register_ui_size_event_callback(callback: Rc<dyn Fn(f64, f64)>) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_SIZE_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_size_event_callback(id: usize, width: f64, height: f64) {
    // See `invoke_ui_event_callback`'s doc comment — same re-entrancy hazard, same fix.
    let callback = UI_SIZE_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback(width, height);
    }
}

#[cfg(test)]
pub(crate) fn ui_size_event_callback_count() -> usize {
    UI_SIZE_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().len())
}

/// Distinguishes a model-to-native property push from a real user-originated XAML event.
///
/// WinUI dependency-property setters synchronously raise the same change events used for input.
/// Each native control wraps its setter calls in `suppress`, and its TLS callback checks
/// `is_suppressed`, so a two-way binding does not immediately echo its own value back to the
/// model. The previous state is restored by `Drop`, including during unwinding and nested pushes.
#[derive(Clone, Default)]
pub(crate) struct UiEventGate(Rc<Cell<bool>>);

impl UiEventGate {
    pub(crate) fn is_suppressed(&self) -> bool {
        self.0.get()
    }

    pub(crate) fn suppress<T>(&self, callback: impl FnOnce() -> T) -> T {
        struct Restore<'a> {
            cell: &'a Cell<bool>,
            previous: bool,
        }

        impl Drop for Restore<'_> {
            fn drop(&mut self) {
                self.cell.set(self.previous);
            }
        }

        let previous = self.0.replace(true);
        let _restore = Restore {
            cell: &self.0,
            previous,
        };
        callback()
    }
}

pub(crate) fn register_ui_key_event_callback(callback: Rc<dyn Fn(RawKeyEvent)>) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_KEY_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_key_event_callback(id: usize, event: RawKeyEvent) {
    // See `invoke_ui_event_callback`'s doc comment — same re-entrancy hazard, same fix.
    let callback = UI_KEY_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback(event);
    }
}

pub(crate) fn register_ui_text_event_callback(callback: Rc<dyn Fn(String)>) -> usize {
    let id = NEXT_UI_EVENT_CALLBACK.fetch_add(1, Ordering::Relaxed);
    UI_TEXT_EVENT_CALLBACKS.with(|callbacks| {
        callbacks.borrow_mut().insert(id, callback);
    });
    id
}

pub(crate) fn invoke_ui_text_event_callback(id: usize, text: String) {
    // See `invoke_ui_event_callback`'s doc comment — same re-entrancy hazard, same fix.
    let callback = UI_TEXT_EVENT_CALLBACKS.with(|callbacks| callbacks.borrow().get(&id).cloned());
    if let Some(callback) = callback {
        callback(text);
    }
}

/// The capability a type needs to be usable as an `AnyView` — implemented once per raw XAML element
/// type (`XamlTextBox`/`XamlButton`/`XamlTabView`) instead of matched on centrally, so a future native
/// leaf (`Dialog`, `VirtualList`, ...) only needs its own `impl WinUiHandle`, never a change to
/// `AnyView` itself or to any `match` over it — mirrors `elwindui-backend-appkit`'s `AppKitHandle`
/// (see that trait's own doc comment for the rationale).
///
/// Implemented on the raw XAML element type itself (a foreign type — allowed since `WinUiHandle` is
/// a local trait) rather than on `TextArea`/`Button`/`NativeTabView`, since those now each
/// compose this crate's own `NativeControl` (see `native_ui.rs`) as their own `base` field
/// (docs/design/runtime/ui_tree_design.md) — an `AnyView` wrapping the not-yet-fully-constructed widget
/// itself would be a self-reference. Wrapping just the raw element instead lets `base.handle` be
/// built (`AnyView::from(xaml.clone())`) before the rest of the widget struct exists.
pub(crate) trait WinUiHandle: elwindui_core::base::AsAny {
    fn as_element(&self) -> FrameworkElement;

    /// Applies an explicit background or clears it back to the native control default.
    fn apply_background(
        &self,
        background: Option<&elwindui_core::graphics::Brush>,
    ) -> windows::core::Result<()> {
        let control: crate::bindings::Microsoft::UI::Xaml::Controls::Control =
            self.as_element().cast()?;
        crate::render::apply_control_background(&control, background)
    }

    /// Pushes a resolved text style onto the real widget this handle wraps. No-op by default — a
    /// handle with no text of its own (`XamlTabView`) simply doesn't participate. See
    /// `elwindui-backend-appkit::ffi::AppKitHandle::apply_text_style`'s own doc comment for the
    /// full pull-based rationale this mirrors — identical here. **Unverifiable on this machine**;
    /// see `render::text`'s own doc comment.
    fn apply_text_style(
        &self,
        _style: &elwindui_core::graphics::CascadedTextStyle,
    ) -> windows::core::Result<()> {
        Ok(())
    }

    /// Whether this handle actually has somewhere to put a text style (指示書 §17: never treat
    /// "discarded" as "applied").
    fn supports_text_style(&self) -> bool {
        false
    }
}

impl WinUiHandle for XamlTextBox {
    fn as_element(&self) -> FrameworkElement {
        self.cast().expect("TextBox implements FrameworkElement")
    }
    fn apply_text_style(
        &self,
        style: &elwindui_core::graphics::CascadedTextStyle,
    ) -> windows::core::Result<()> {
        let control: crate::bindings::Microsoft::UI::Xaml::Controls::Control =
            self.cast().expect("TextBox implements Control");
        crate::render::apply_cascaded_text_style_to_control(&control, style)
    }
    fn supports_text_style(&self) -> bool {
        true
    }
}

impl WinUiHandle for XamlPasswordBox {
    fn as_element(&self) -> FrameworkElement {
        self.cast()
            .expect("PasswordBox implements FrameworkElement")
    }
    fn apply_text_style(
        &self,
        style: &elwindui_core::graphics::CascadedTextStyle,
    ) -> windows::core::Result<()> {
        let control: crate::bindings::Microsoft::UI::Xaml::Controls::Control =
            self.cast().expect("PasswordBox implements Control");
        crate::render::apply_cascaded_text_style_to_control(&control, style)
    }
    fn supports_text_style(&self) -> bool {
        true
    }
}

impl WinUiHandle for ScrollViewer {
    fn as_element(&self) -> FrameworkElement {
        self.cast()
            .expect("ScrollViewer implements FrameworkElement")
    }
    fn apply_text_style(
        &self,
        style: &elwindui_core::graphics::CascadedTextStyle,
    ) -> windows::core::Result<()> {
        // `ScrollView`'s own content is a nested `ElwinduiContentRoot` host, not text — mirrors
        // `elwindui-backend-appkit`'s identical `NSScrollView` no-op for the `ScrollView` case.
        // `ScrollViewer` still derives `Control`, so pushing the style is harmless (it would only
        // ever matter if some future hosted-content font-inheritance path read it back), and
        // costs nothing to keep consistent with the other three handles.
        let control: crate::bindings::Microsoft::UI::Xaml::Controls::Control =
            self.cast().expect("ScrollViewer implements Control");
        crate::render::apply_cascaded_text_style_to_control(&control, style)
    }
    fn supports_text_style(&self) -> bool {
        false
    }
}

impl WinUiHandle for XamlButton {
    fn as_element(&self) -> FrameworkElement {
        self.cast().expect("Button implements FrameworkElement")
    }
    fn apply_text_style(
        &self,
        style: &elwindui_core::graphics::CascadedTextStyle,
    ) -> windows::core::Result<()> {
        let control: crate::bindings::Microsoft::UI::Xaml::Controls::Control =
            self.cast().expect("Button implements Control");
        crate::render::apply_cascaded_text_style_to_control(&control, style)
    }
    fn supports_text_style(&self) -> bool {
        true
    }
}

macro_rules! impl_button_like_handle {
    ($ty:ty, $name:literal) => {
        impl WinUiHandle for $ty {
            fn as_element(&self) -> FrameworkElement {
                self.cast()
                    .expect(concat!($name, " implements FrameworkElement"))
            }
            fn apply_text_style(
                &self,
                style: &elwindui_core::graphics::CascadedTextStyle,
            ) -> windows::core::Result<()> {
                let control: crate::bindings::Microsoft::UI::Xaml::Controls::Control =
                    self.cast().expect(concat!($name, " implements Control"));
                crate::render::apply_cascaded_text_style_to_control(&control, style)
            }
            fn supports_text_style(&self) -> bool {
                true
            }
        }
    };
}

impl_button_like_handle!(XamlCheckBox, "CheckBox");
impl_button_like_handle!(XamlRadioButton, "RadioButton");

macro_rules! impl_textless_control_handle {
    ($ty:ty, $name:literal) => {
        impl WinUiHandle for $ty {
            fn as_element(&self) -> FrameworkElement {
                self.cast()
                    .expect(concat!($name, " implements FrameworkElement"))
            }
        }
    };
}

impl_textless_control_handle!(XamlToggleSwitch, "ToggleSwitch");
impl_textless_control_handle!(XamlComboBox, "ComboBox");
impl_textless_control_handle!(XamlSlider, "Slider");

impl WinUiHandle for XamlTabView {
    fn as_element(&self) -> FrameworkElement {
        self.cast().expect("TabView implements FrameworkElement")
    }
}

/// Everything the generated code can pass as a `Window`/`NativeTabView` child.
/// `VerticalLayout`/`HorizontalLayout`/`Rectangle`/`Ellipse`/`TextBlock` have no variant here —
/// they're purely `elwindui_core::ui::UIElement` values (see `TreeHostPanel` below). An
/// `Rc<dyn WinUiHandle>` (not a closed `enum`) so adding a new native leaf never requires touching
/// this type — see `WinUiHandle`'s own doc comment. Re-exported at the crate root (`lib.rs`) since
/// `elwindui-codegen`'s generated code references `elwindui::backend::AnyView` directly.
#[derive(Clone)]
pub struct AnyView(Rc<dyn WinUiHandle>);

impl AnyView {
    pub(crate) fn as_element(&self) -> FrameworkElement {
        self.0.as_element()
    }

    /// Forwards to the wrapped handle's own `WinUiHandle::apply_text_style` — called by
    /// `NativeControl::sync_text_style` (`native_ui/control.rs`).
    pub(crate) fn apply_text_style(
        &self,
        style: &elwindui_core::graphics::CascadedTextStyle,
    ) -> windows::core::Result<()> {
        self.0.apply_text_style(style)
    }

    /// Forwards to the wrapped handle's own `WinUiHandle::supports_text_style`.
    pub(crate) fn supports_text_style(&self) -> bool {
        self.0.supports_text_style()
    }

    /// Applies an explicit background or restores the native toolkit default.
    pub(crate) fn apply_background(
        &self,
        background: Option<&elwindui_core::graphics::Brush>,
    ) -> windows::core::Result<()> {
        self.0.apply_background(background)
    }

    /// Sets (or, with `None`, removes) this control's hover tooltip.
    ///
    /// Not an `WinUi3Handle` method: `ToolTipService` is an attached property on
    /// `DependencyObject`, so one implementation on the base element covers every wrapped widget
    /// and no per-handle `impl` needs to know about it — the AppKit backend's own
    /// `AnyView::set_tooltip` (`NSView.toolTip`) mirrors this exactly.
    pub(crate) fn set_tooltip(&self, tooltip: Option<&str>) -> windows::core::Result<()> {
        let element = self.as_element();
        match tooltip {
            Some(text) => {
                let value = PropertyValue::CreateString(&HSTRING::from(text))?;
                let tooltip = XamlToolTip::new()?;
                tooltip.SetContent(&value)?;
                ToolTipService::SetToolTip(&element, &tooltip)
            }
            None => ToolTipService::SetToolTip(&element, None),
        }
    }
}

impl AnyView {
    /// Lets `NativeControl::measure_override` (in `native_ui.rs` — shared by every `TextArea`/
    /// `Button`/`TabView` leaf) measure any wrapped widget uniformly through the base
    /// `FrameworkElement`/`UIElement` API regardless of which concrete widget it wraps — no
    /// per-widget re-implementation of the actual `Measure`/`DesiredSize` calls needed. A plain
    /// inherent method, not a shared `elwindui-core`-defined trait — measuring a native handle is
    /// entirely backend-specific, so `elwindui_core::ui::NativeControl` (a pure marker trait)
    /// doesn't know how to do it.
    pub(crate) fn measure(
        &self,
        available: elwindui_core::base::Size,
    ) -> elwindui_core::base::Size {
        let element = self.as_element();
        // `arrange` (below) sets an explicit `Width`/`Height` on this same `FrameworkElement` so a
        // plain `Canvas` (which has no native measure-driven arrange of its own) gives it concrete
        // bounds. That explicit size persists across relayout passes and, once set, permanently
        // overrides the element's own natural/content-driven measurement — a `FrameworkElement`
        // with an explicit `Width` always reports that `Width` from `Measure()` regardless of
        // content, clamped to (not derived from) `available`. Without resetting it back to
        // `NaN` ("unset"/Auto) here first, the very first relayout pass — where `available` is
        // `{0, 0}` before the window has a real size — sets `Width`/`Height` to 0 via `arrange`,
        // and every subsequent `Measure` call then reports `DesiredSize` of 0 forever, regardless
        // of how large `available` later becomes: a self-reinforcing feedback loop, not a one-time
        // glitch. (Containers that arrange children from an external allocation independent of the
        // child's own measured size — e.g. a `Grid` `Star` row — escape this, since their own
        // `arrange` overwrites `Width`/`Height` with that external allocation every pass regardless
        // of what `Measure` last reported; content-driven/Auto containers, whose `arrange` derives
        // each child's final size *from* that same child's `DesiredSize`, do not.)
        let _ = element.SetWidth(f64::NAN);
        let _ = element.SetHeight(f64::NAN);
        // `SetWidth`/`SetHeight` alone mark the element measure-dirty going forward, but don't
        // retroactively guarantee *this* `Measure` call re-runs the native measure pass rather than
        // short-circuiting on a still-cached `DesiredSize` from before the reset — invalidate
        // explicitly so the call below is never skipped.
        let _ = element.InvalidateMeasure();
        let _ = element.Measure(Size {
            Width: available.width as f32,
            Height: available.height as f32,
        });
        let desired = element.DesiredSize().unwrap_or(Size {
            Width: 0.0,
            Height: 0.0,
        });
        elwindui_core::base::Size {
            width: desired.Width,
            height: desired.Height,
        }
    }

    /// Positions this native leaf — like `measure` above, a plain inherent method (elwindui-core's
    /// generic layout code never calls either) — called directly by `TreeHostPanel`'s own render
    /// loop below, after `layout_root` and RenderTree reconciliation have produced its native
    /// command. Unlike AppKit (where `arrange` calls `setFrame` directly),
    /// a `Canvas`'s children are still measured/arranged by the real XAML layout system on every
    /// layout pass — this only needs to set the `Width`/`Height` and `Canvas.Left`/`Canvas.Top`
    /// attached properties once; `Canvas`'s own (built-in) `ArrangeOverride` does the rest, unlike
    /// AppKit's plain `NSView` which has no attached-property positioning at all.
    pub(crate) fn arrange(&mut self, final_rect: elwindui_core::base::Rect) {
        let element = self.as_element();
        let _ = element.SetWidth(final_rect.width as f64);
        let _ = element.SetHeight(final_rect.height as f64);
        let _ = Canvas::SetLeft(&element, final_rect.x as f64);
        let _ = Canvas::SetTop(&element, final_rect.y as f64);
    }
}

impl<T: WinUiHandle + 'static> From<T> for AnyView {
    fn from(v: T) -> Self {
        AnyView(Rc::new(v))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn callback_registry_owner_unregisters_on_final_drop() {
        let calls = Rc::new(Cell::new(0));
        let owner = UiCallbackRegistryOwner::default();
        let owner_clone = owner.clone();
        let calls_for_callback = calls.clone();
        let id = owner.register_event(Rc::new(move || {
            calls_for_callback.set(calls_for_callback.get() + 1);
        }));

        invoke_ui_event_callback(id);
        assert_eq!(calls.get(), 1);
        drop(owner);
        invoke_ui_event_callback(id);
        assert_eq!(calls.get(), 2, "a clone must keep the registration alive");
        drop(owner_clone);
        invoke_ui_event_callback(id);
        assert_eq!(calls.get(), 2, "a removed id must be a safe no-op");
    }

    #[test]
    fn callback_registry_owner_unregisters_each_callback_kind() {
        let owner = UiCallbackRegistryOwner::default();
        let index_calls = Rc::new(Cell::new(0));
        let text_calls = Rc::new(Cell::new(0));
        let index_calls_for_callback = index_calls.clone();
        let text_calls_for_callback = text_calls.clone();
        let index_id = owner.register_index(Rc::new(move |value| {
            index_calls_for_callback.set(value);
        }));
        let text_id = owner.register_text(Rc::new(move |value| {
            text_calls_for_callback.set(value.len());
        }));

        invoke_ui_index_event_callback(index_id, 7);
        invoke_ui_text_event_callback(text_id, "abc".to_string());
        assert_eq!(index_calls.get(), 7);
        assert_eq!(text_calls.get(), 3);
        drop(owner);
        invoke_ui_index_event_callback(index_id, 9);
        invoke_ui_text_event_callback(text_id, "ignored".to_string());
        assert_eq!(index_calls.get(), 7);
        assert_eq!(text_calls.get(), 3);
    }

    #[test]
    fn callback_registry_owner_repeated_lifecycles_return_to_baseline() {
        let baseline = ui_event_callback_count();

        for _ in 0..8 {
            let calls = Rc::new(Cell::new(0));
            let calls_for_callback = calls.clone();
            let owner = UiCallbackRegistryOwner::default();
            let id = owner.register_event(Rc::new(move || {
                calls_for_callback.set(calls_for_callback.get() + 1);
            }));

            assert_eq!(ui_event_callback_count(), baseline + 1);
            invoke_ui_event_callback(id);
            assert_eq!(calls.get(), 1);

            drop(owner);
            assert_eq!(ui_event_callback_count(), baseline);
            invoke_ui_event_callback(id);
            assert_eq!(calls.get(), 1);
        }
    }

    #[test]
    fn callback_invocation_can_register_and_remove_another_callback() {
        let calls = Rc::new(Cell::new(0));
        let nested_calls = Rc::clone(&calls);
        let id = register_ui_event_callback(Rc::new(move || {
            nested_calls.set(nested_calls.get() + 1);
        }));
        let callback_calls = Rc::clone(&calls);
        let outer_id = register_ui_event_callback(Rc::new(move || {
            callback_calls.set(callback_calls.get() + 1);
            let nested_id = register_ui_event_callback(Rc::new(|| {}));
            invoke_ui_event_callback(id);
            remove_ui_callback(UiCallbackKind::Event, nested_id);
        }));

        invoke_ui_event_callback(outer_id);
        assert_eq!(calls.get(), 2);
        remove_ui_callback(UiCallbackKind::Event, id);
        remove_ui_callback(UiCallbackKind::Event, outer_id);
    }

    /// T1/T2 (Issue #225 post-merge review, PR #227): `UiCallbackRegistryOwner::register_size`
    /// tracks its id like every other kind, and the registered callback observes the exact
    /// `(width, height)` it was invoked with.
    #[test]
    fn size_callback_registration_and_invocation_use_exact_values() {
        let baseline = ui_size_event_callback_count();
        let observed = Rc::new(Cell::new((0.0_f64, 0.0_f64)));
        let owner = UiCallbackRegistryOwner::default();
        let observed_for_callback = observed.clone();
        let id = owner.register_size(Rc::new(move |width, height| {
            observed_for_callback.set((width, height));
        }));

        assert_eq!(ui_size_event_callback_count(), baseline + 1);
        invoke_ui_size_event_callback(id, 640.0, 480.0);
        assert_eq!(observed.get(), (640.0, 480.0));
    }

    /// T3: dropping the owning `UiCallbackRegistryOwner` removes the `Size` TLS entry (not just
    /// "no panic on the next invocation") — this is exactly the lifetime leak PR #227 introduced,
    /// since `register_ui_size_event_callback` was called directly, untracked, from
    /// `InnerWindow::new`.
    #[test]
    fn size_callback_owner_drop_removes_entry_and_id_becomes_no_op() {
        let baseline = ui_size_event_callback_count();
        let observed = Rc::new(Cell::new((0.0_f64, 0.0_f64)));
        let owner = UiCallbackRegistryOwner::default();
        let observed_for_callback = observed.clone();
        let id = owner.register_size(Rc::new(move |width, height| {
            observed_for_callback.set((width, height));
        }));

        invoke_ui_size_event_callback(id, 100.0, 200.0);
        assert_eq!(observed.get(), (100.0, 200.0));

        drop(owner);
        assert_eq!(
            ui_size_event_callback_count(),
            baseline,
            "dropping the owner must remove the Size registry entry, not just leave it unreachable"
        );

        invoke_ui_size_event_callback(id, 999.0, 999.0);
        assert_eq!(
            observed.get(),
            (100.0, 200.0),
            "invoking a removed id must be a safe no-op that does not reach the old callback"
        );
    }

    /// T4: the leak regression itself — repeated Window-like create/destroy cycles must not
    /// monotonically grow `UI_SIZE_EVENT_CALLBACKS`.
    #[test]
    fn size_callback_repeated_lifecycles_return_to_baseline() {
        let baseline = ui_size_event_callback_count();

        for _ in 0..8 {
            let calls = Rc::new(Cell::new(0));
            let calls_for_callback = calls.clone();
            let owner = UiCallbackRegistryOwner::default();
            let id = owner.register_size(Rc::new(move |_width, _height| {
                calls_for_callback.set(calls_for_callback.get() + 1);
            }));

            assert_eq!(ui_size_event_callback_count(), baseline + 1);
            invoke_ui_size_event_callback(id, 1.0, 2.0);
            assert_eq!(calls.get(), 1);

            drop(owner);
            assert_eq!(ui_size_event_callback_count(), baseline);
            invoke_ui_size_event_callback(id, 3.0, 4.0);
            assert_eq!(calls.get(), 1);
        }
    }
}
