[package]
name = "elwindui-bridge-fixture-backend"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
elwindui-core = { path = "../elwindui-core" }
elwindui-macros = { path = "../elwindui-macros" }
elwindui-bridge-fixture-iface = { path = "../elwindui-bridge-fixture-iface" }

[lints]
workspace = true
