//! `ContentPresenter` visually places a templated `ContentControl`'s logical content.

use super::*;
use crate::reactive::Subscription;

/// A template primitive that presents one `ContentControl` logical content value as a Visual child.
///
/// The binding entrypoint is generated by `#[elwindui::control_template]`; ordinary application
/// code declares the presenter as `ContentPresenter {}` inside a template body.
#[elwindui_macros::class(inherits = crate::ui::Control)]
pub struct ContentPresenter {
    presented_content: RefCell<Option<Rc<dyn UIElementExt>>>,
    content_subscription: RefCell<Option<Subscription>>,
}

#[elwindui_macros::class]
impl ContentPresenter {
    fn construct() -> Self {
        Self {
            base: Control::construct(),
            presented_content: RefCell::new(None),
            content_subscription: RefCell::new(None),
        }
    }
}

impl ContentPresenter {
    fn replace_presented_content(&self, content: Option<Rc<dyn UIElementExt>>) {
        let old = self.presented_content.borrow_mut().take();
        if let Some(old) = old {
            self.as_ui_element().visual_collection.remove(&old);
        }
        if let Some(content) = content {
            self.as_ui_element().visual_collection.add(content.clone());
            *self.presented_content.borrow_mut() = Some(content);
        }
    }

    /// Binds this presenter to a concrete templated `ContentControl` target.
    ///
    /// This method is public only because proc-macro output runs in the consumer crate.
    #[doc(hidden)]
    pub fn __bind_templated_parent<C>(this: &Rc<Self>, source: &Rc<C>)
    where
        C: ContentControlExt + 'static,
    {
        this.content_subscription.borrow_mut().take();
        this.replace_presented_content(source.__content_opt());

        let weak_presenter = Rc::downgrade(this);
        let subscription = source.__subscribe_content_changed(Rc::new(move |content| {
            if let Some(presenter) = weak_presenter.upgrade() {
                presenter.replace_presented_content(content);
            }
        }));
        *this.content_subscription.borrow_mut() = Some(subscription);
    }
}
