//! Rust-only frontend for `#[elwindui::environment_key]`.
//!
//! Mirrors `theme_frontend.rs`'s shape: an Environment Key declaration does not enter the DSL
//! AST/parser either. This module consumes a `syn::ItemStruct` (a unit struct — the Key is a
//! marker type, never instantiated) and emits its `EnvironmentKey` implementation, then registers
//! `name` into the same-crate registry `#[environment(name)]`/`EnvironmentScope` resolve against
//! (`component_frontend::register_same_crate_environment_key`).
//!
//! It also exports a `__elwindui_environment_key_{name}!` declarative macro (Issue #129,
//! `docs/design/tools/environment_key_macro_design.md`) — the cross-crate counterpart to the
//! same-crate registry, carrying the Key type across the crate boundary the same way `#[class]`'s
//! own `__elwindui_props_*!`/`__elwindui_inherit_*!` macros do (`docs/design/tools/
//! class_macro_design.md` "Shape macro protocol"), mirrored down to a single flat macro per Key
//! (no ancestor-chain forwarding is needed here, so — unlike `#[class]`'s macros — this one needs
//! no catch-all arm and no `#[allow(macro_expanded_macro_exports_accessed_by_absolute_paths)]`).
//!
//! See `docs/specs/theme_environment_spec.md` §2 and `docs/specs/dsl_spec.md` §4/§5.

use crate::component_frontend::register_same_crate_environment_key;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::parse::{Parse, ParseStream};
use syn::{Expr, Ident, ItemStruct, Token, Type};

struct EnvironmentKeyArgs {
    name: Ident,
    value: Type,
    default: Expr,
}

impl Parse for EnvironmentKeyArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let mut name = None;
        let mut value = None;
        let mut default = None;
        while !input.is_empty() {
            let key: Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            if key == "name" {
                if name.replace(input.parse()?).is_some() {
                    return Err(syn::Error::new(key.span(), "duplicate `name` argument"));
                }
            } else if key == "value" {
                if value.replace(input.parse()?).is_some() {
                    return Err(syn::Error::new(key.span(), "duplicate `value` argument"));
                }
            } else if key == "default" {
                if default.replace(input.parse()?).is_some() {
                    return Err(syn::Error::new(key.span(), "duplicate `default` argument"));
                }
            } else {
                return Err(syn::Error::new(
                    key.span(),
                    "expected `name = ..`, `value = ..`, or `default = ..`",
                ));
            }
            if !input.is_empty() {
                input.parse::<Token![,]>()?;
            }
        }
        Ok(Self {
            name: name.ok_or_else(|| input.error("missing `name = ..`"))?,
            value: value.ok_or_else(|| input.error("missing `value = ..`"))?,
            default: default.ok_or_else(|| input.error("missing `default = ..`"))?,
        })
    }
}

pub fn generate_environment_key_from_item_struct(
    args: TokenStream,
    item: &ItemStruct,
) -> Result<TokenStream, String> {
    let args = syn::parse2::<EnvironmentKeyArgs>(args).map_err(|error| error.to_string())?;
    if !item.generics.params.is_empty() {
        return Err("environment key structs cannot be generic".into());
    }
    if !matches!(item.fields, syn::Fields::Unit) {
        return Err(format!(
            "`{}`: an `#[elwindui::environment_key]` struct must be a unit struct (`struct {};`) \
             — it is a marker type, never instantiated",
            item.ident, item.ident
        ));
    }

    let visibility = &item.vis;
    let ident = &item.ident;
    let key_name = args.name.to_string();
    let value_ty = &args.value;
    let default_expr = &args.default;

    register_same_crate_environment_key(
        &key_name,
        &ident.to_string(),
        &quote!(#value_ty).to_string(),
    )
    .map_err(|error| format!("`{ident}`: {error}"))?;

    let doc = format!(
        "Environment Key `{key_name}`, generated by `#[elwindui::environment_key]`. See \
         `docs/specs/theme_environment_spec.md` §2."
    );

    // Cross-crate counterpart to the same-crate registry above (Issue #129): a consuming crate's
    // `#[environment(this_crate::{key_name})]`/`EnvironmentScope { this_crate::{key_name}: .. }`
    // invokes this by name (`codegen::environment_key_type_by_name`) to splice `$ident` into type
    // position. `$crate` (not a literal `crate`/bare `#ident`) is required precisely because this
    // macro is meant to be invoked from a *different* crate than the one it's defined in — it always
    // resolves to the crate that defines this `macro_rules!` item, regardless of where it's called
    // from (`docs/design/tools/environment_key_macro_design.md`).
    let macro_ident = format_ident!("__elwindui_environment_key_{key_name}");
    let macro_doc = format!(
        "Cross-crate resolution macro for Environment Key `{key_name}` (Issue #129). Not \
         user-facing API — invoked only by `elwindui-codegen`'s generated code for a qualified \
         `#[environment(..)]`/`EnvironmentScope` reference."
    );

    Ok(quote! {
        #[doc = #doc]
        #visibility struct #ident;

        impl elwindui::core::environment::EnvironmentKey for #ident {
            type Value = #value_ty;

            fn default_value() -> Self::Value {
                #default_expr
            }
        }

        #[doc(hidden)]
        #[doc = #macro_doc]
        #[macro_export]
        macro_rules! #macro_ident {
            () => {
                $crate::#ident
            };
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;

    #[test]
    fn generates_environment_key_impl() {
        let item: ItemStruct = syn::parse_quote! {
            pub struct LocaleEnvironment;
        };
        let output = generate_environment_key_from_item_struct(
            quote!(
                name = locale_for_test_generates_impl,
                value = String,
                default = String::from("en-US")
            ),
            &item,
        )
        .unwrap()
        .to_string();
        assert!(output.contains(
            "impl elwindui :: core :: environment :: EnvironmentKey for LocaleEnvironment"
        ));
        assert!(output.contains("type Value = String"));
        assert!(output.contains("en-US"));
    }

    #[test]
    fn rejects_non_unit_struct() {
        let item: ItemStruct = syn::parse_quote! {
            pub struct LocaleEnvironment {
                extra: String,
            }
        };
        let error = generate_environment_key_from_item_struct(
            quote!(
                name = locale_for_test_rejects_non_unit,
                value = String,
                default = String::new()
            ),
            &item,
        )
        .unwrap_err();
        assert!(error.contains("unit struct"));
    }

    #[test]
    fn rejects_missing_argument() {
        let item: ItemStruct = syn::parse_quote! {
            pub struct LocaleEnvironment;
        };
        let error = generate_environment_key_from_item_struct(
            quote!(name = locale_for_test_rejects_missing, value = String),
            &item,
        )
        .unwrap_err();
        assert!(error.contains("missing `default"));
    }
}
